# Generated by Django 4.1.7 on 2024-02-29 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('bajaj', 'Bajaj'), ('minibus', 'Minibus'), ('bicycle', 'Bicycle')], max_length=10)),
                ('address', models.CharField(choices=[('mekele', 'Mekele'), ('adigrat', 'Adigrat'), ('adwa', 'Adwa'), ('aa', 'AA')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('license_plate', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
