# Generated by Django 4.1.7 on 2024-02-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_location',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
