# Generated by Django 4.1.7 on 2024-03-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_driver_current_location_driver_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='current_location',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('accepted', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rider')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rider')),
            ],
        ),
    ]
